# TCL File Generated by Component Editor 13.0sp1
# Mon Aug 26 18:01:34 PDT 2013
# DO NOT MODIFY


# 
# xcvr_st_converter "xcvr_st_converter" v1.0
#  2013.08.26.18:01:33
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module xcvr_st_converter
# 
set_module_property DESCRIPTION ""
set_module_property NAME xcvr_st_converter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME xcvr_st_converter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property GROUP Devkit_IPs


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL xcvr_st_converter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file xcvr_st_converter.v VERILOG PATH xcvr_st_converter.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL xcvr_st_converter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file xcvr_st_converter.v VERILOG PATH xcvr_st_converter.v


# 
# parameters
# 
add_parameter DATAWIDTH INTEGER 40
set_parameter_property DATAWIDTH DEFAULT_VALUE 40
set_parameter_property DATAWIDTH DISPLAY_NAME DATAWIDTH
set_parameter_property DATAWIDTH TYPE INTEGER
set_parameter_property DATAWIDTH UNITS None
set_parameter_property DATAWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATAWIDTH HDL_PARAMETER true
add_parameter NUM_OF_CH INTEGER 1
set_parameter_property NUM_OF_CH DEFAULT_VALUE 1
set_parameter_property NUM_OF_CH DISPLAY_NAME NUM_OF_CH
set_parameter_property NUM_OF_CH TYPE INTEGER
set_parameter_property NUM_OF_CH UNITS None
set_parameter_property NUM_OF_CH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_OF_CH HDL_PARAMETER true


# 
# display items
# 

# 
# connection point tx_parallel_data
# 
add_interface tx_parallel_data conduit end
set_interface_property tx_parallel_data associatedClock ""
set_interface_property tx_parallel_data associatedReset ""
set_interface_property tx_parallel_data ENABLED true
set_interface_property tx_parallel_data EXPORT_OF ""
set_interface_property tx_parallel_data PORT_NAME_MAP ""
set_interface_property tx_parallel_data SVD_ADDRESS_GROUP ""

add_interface_port tx_parallel_data tx_parallel_data tx_parallel_data Output DATAWIDTH*NUM_OF_CH


# 
# connection point tx_clkout
#
add_interface tx_clkout clock end
set_interface_property tx_clkout clockRate 0
set_interface_property tx_clkout ENABLED true
set_interface_property tx_clkout EXPORT_OF ""
set_interface_property tx_clkout PORT_NAME_MAP ""
set_interface_property tx_clkout SVD_ADDRESS_GROUP ""

add_interface_port tx_clkout tx_clkout clk Input NUM_OF_CH



# 
# connection point rx_parallel_data
# 
add_interface rx_parallel_data conduit end
set_interface_property rx_parallel_data associatedClock ""
set_interface_property rx_parallel_data associatedReset ""
set_interface_property rx_parallel_data ENABLED true
set_interface_property rx_parallel_data EXPORT_OF ""
set_interface_property rx_parallel_data PORT_NAME_MAP ""
set_interface_property rx_parallel_data SVD_ADDRESS_GROUP ""

add_interface_port rx_parallel_data rx_parallel_data rx_parallel_data Input DATAWIDTH*NUM_OF_CH

# 
# connection point rx_clkout
# 
add_interface rx_clkout clock end
set_interface_property rx_clkout clockRate 0
set_interface_property rx_clkout ENABLED true
set_interface_property rx_clkout EXPORT_OF ""
set_interface_property rx_clkout PORT_NAME_MAP ""
set_interface_property rx_clkout SVD_ADDRESS_GROUP ""

add_interface_port rx_clkout rx_clkout clk Input NUM_OF_CH





set_module_property ELABORATION_CALLBACK    elaborate_me








proc elaborate_me {}  {


		
  if { [get_parameter_value NUM_OF_CH] >= 1 }  {

		add_interface tx_data_a conduit end
		set_interface_property tx_data_a associatedClock ""
		set_interface_property tx_data_a associatedReset ""
		set_interface_property tx_data_a ENABLED true
		set_interface_property tx_data_a EXPORT_OF ""
		set_interface_property tx_data_a PORT_NAME_MAP ""
		set_interface_property tx_data_a SVD_ADDRESS_GROUP ""

		add_interface_port tx_data_a tx_data_a export Input DATAWIDTH*4/5

		add_interface tx_clkout_a conduit end
		set_interface_property tx_clkout_a associatedClock ""
		set_interface_property tx_clkout_a associatedReset ""
		set_interface_property tx_clkout_a ENABLED true
		set_interface_property tx_clkout_a EXPORT_OF ""
		set_interface_property tx_clkout_a PORT_NAME_MAP ""
		set_interface_property tx_clkout_a SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_a tx_clkout_a export Output 1


		
		add_interface rx_data_a conduit end
		set_interface_property rx_data_a associatedClock ""
		set_interface_property rx_data_a associatedReset ""
		set_interface_property rx_data_a ENABLED true
		set_interface_property rx_data_a EXPORT_OF ""
		set_interface_property rx_data_a PORT_NAME_MAP ""
		set_interface_property rx_data_a SVD_ADDRESS_GROUP ""

		add_interface_port rx_data_a rx_data_a export Output DATAWIDTH*4/5

		
		add_interface rx_clkout_a conduit end
		set_interface_property rx_clkout_a associatedClock ""
		set_interface_property rx_clkout_a associatedReset ""
		set_interface_property rx_clkout_a ENABLED true
		set_interface_property rx_clkout_a EXPORT_OF ""
		set_interface_property rx_clkout_a PORT_NAME_MAP ""
		set_interface_property rx_clkout_a SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_a rx_clkout_a export Output 1

        add_interface tx_clkout_sample clock start
		set_interface_property tx_clkout_sample associatedDirectClock ""
		set_interface_property tx_clkout_sample clockRate 0
		set_interface_property tx_clkout_sample clockRateKnown false
		set_interface_property tx_clkout_sample ENABLED true
		set_interface_property tx_clkout_sample EXPORT_OF ""
		set_interface_property tx_clkout_sample PORT_NAME_MAP ""
		set_interface_property tx_clkout_sample SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_sample tx_clkout_sample clk Output 1

		

		add_interface tx_clkout_a_output clock start
		set_interface_property tx_clkout_a_output associatedDirectClock ""
		set_interface_property tx_clkout_a_output clockRate 0
		set_interface_property tx_clkout_a_output clockRateKnown false
		set_interface_property tx_clkout_a_output ENABLED true
		set_interface_property tx_clkout_a_output EXPORT_OF ""
		set_interface_property tx_clkout_a_output PORT_NAME_MAP ""
		set_interface_property tx_clkout_a_output SVD_ADDRESS_GROUP ""

		add_interface_port tx_clkout_a_output tx_clkout_a_output clk Output 1
		
		add_interface rx_clkout_a_output clock start
		set_interface_property rx_clkout_a_output associatedDirectClock ""
		set_interface_property rx_clkout_a_output clockRate 0
		set_interface_property rx_clkout_a_output clockRateKnown false
		set_interface_property rx_clkout_a_output ENABLED true
		set_interface_property rx_clkout_a_output EXPORT_OF ""
		set_interface_property rx_clkout_a_output PORT_NAME_MAP ""
		set_interface_property rx_clkout_a_output SVD_ADDRESS_GROUP ""

		add_interface_port rx_clkout_a_output rx_clkout_a_output clk Output 1
	}

  
}









