// ftile_xcvr_test_xcvr_conduit_ctrl_0.v

// Generated using ACDS version 24.2 40

`timescale 1 ps / 1 ps
module ftile_xcvr_test_xcvr_conduit_ctrl_0 (
		input  wire        reset_n,            //              reset.reset_n
		input  wire        clk,                //              clock.clk
		input  wire [3:0]  csr_address,        //                csr.address
		input  wire        csr_read,           //                   .read
		input  wire        csr_write,          //                   .write
		output wire [31:0] csr_readdata,       //                   .readdata
		input  wire [31:0] csr_writedata,      //                   .writedata
		input  wire [0:0]  tx_pll_locked,      //      tx_pll_locked.tx_pll_locked
		input  wire [0:0]  rx_is_lockedtoref,  //  rx_is_lockedtoref.rx_is_lockedtoref
		input  wire [0:0]  rx_is_lockedtodata, // rx_is_lockedtodata.rx_is_lockedtodata
		output wire [0:0]  tx_reset,           //           tx_reset.tx_reset
		input  wire [0:0]  tx_reset_ack,       //       tx_reset_ack.tx_reset_ack
		input  wire [0:0]  tx_ready,           //           tx_ready.tx_ready
		output wire [0:0]  rx_reset,           //           rx_reset.rx_reset
		input  wire [0:0]  rx_reset_ack,       //       rx_reset_ack.rx_reset_ack
		input  wire [0:0]  rx_ready            //           rx_ready.rx_ready
	);

	xcvr_conduit_ctrl xcvr_conduit_ctrl_0 (
		.reset_n            (reset_n),            //   input,   width = 1,              reset.reset_n
		.clk                (clk),                //   input,   width = 1,              clock.clk
		.csr_address        (csr_address),        //   input,   width = 4,                csr.address
		.csr_read           (csr_read),           //   input,   width = 1,                   .read
		.csr_write          (csr_write),          //   input,   width = 1,                   .write
		.csr_readdata       (csr_readdata),       //  output,  width = 32,                   .readdata
		.csr_writedata      (csr_writedata),      //   input,  width = 32,                   .writedata
		.tx_pll_locked      (tx_pll_locked),      //   input,   width = 1,      tx_pll_locked.tx_pll_locked
		.rx_is_lockedtoref  (rx_is_lockedtoref),  //   input,   width = 1,  rx_is_lockedtoref.rx_is_lockedtoref
		.rx_is_lockedtodata (rx_is_lockedtodata), //   input,   width = 1, rx_is_lockedtodata.rx_is_lockedtodata
		.tx_reset           (tx_reset),           //  output,   width = 1,           tx_reset.tx_reset
		.tx_reset_ack       (tx_reset_ack),       //   input,   width = 1,       tx_reset_ack.tx_reset_ack
		.tx_ready           (tx_ready),           //   input,   width = 1,           tx_ready.tx_ready
		.rx_reset           (rx_reset),           //  output,   width = 1,           rx_reset.rx_reset
		.rx_reset_ack       (rx_reset_ack),       //   input,   width = 1,       rx_reset_ack.rx_reset_ack
		.rx_ready           (rx_ready)            //   input,   width = 1,           rx_ready.rx_ready
	);

endmodule
