// ftile_xcvr_test.v

// Generated using ACDS version 24.2 40

`timescale 1 ps / 1 ps
module ftile_xcvr_test (
		input  wire        clk_100_clk,                                     //                           clk_100.clk
		input  wire        reset_100_reset_n,                               //                         reset_100.reset_n
		input  wire        clk_50_clk,                                      //                            clk_50.clk
		input  wire        reset_50_reset_n,                                //                          reset_50.reset_n
		input  wire        directphy_f_0_rx_cdr_refclk_link_clk,            //  directphy_f_0_rx_cdr_refclk_link.clk
		input  wire        directphy_f_0_tx_pll_refclk_link_clk,            //  directphy_f_0_tx_pll_refclk_link.clk
		input  wire [0:0]  directphy_f_0_system_pll_clk_link_clk,           // directphy_f_0_system_pll_clk_link.clk
		output wire [0:0]  directphy_f_0_tx_serial_data_tx_serial_data,     //      directphy_f_0_tx_serial_data.tx_serial_data
		output wire [0:0]  directphy_f_0_tx_serial_data_n_tx_serial_data_n, //    directphy_f_0_tx_serial_data_n.tx_serial_data_n
		input  wire [0:0]  directphy_f_0_rx_serial_data_rx_serial_data,     //      directphy_f_0_rx_serial_data.rx_serial_data
		input  wire [0:0]  directphy_f_0_rx_serial_data_n_rx_serial_data_n, //    directphy_f_0_rx_serial_data_n.rx_serial_data_n
		output wire        mm_bridge_0_s0_waitrequest,                      //                    mm_bridge_0_s0.waitrequest
		output wire [31:0] mm_bridge_0_s0_readdata,                         //                                  .readdata
		output wire        mm_bridge_0_s0_readdatavalid,                    //                                  .readdatavalid
		input  wire [0:0]  mm_bridge_0_s0_burstcount,                       //                                  .burstcount
		input  wire [31:0] mm_bridge_0_s0_writedata,                        //                                  .writedata
		input  wire [20:0] mm_bridge_0_s0_address,                          //                                  .address
		input  wire        mm_bridge_0_s0_write,                            //                                  .write
		input  wire        mm_bridge_0_s0_read,                             //                                  .read
		input  wire [3:0]  mm_bridge_0_s0_byteenable,                       //                                  .byteenable
		input  wire        mm_bridge_0_s0_debugaccess                       //                                  .debugaccess
	);

	wire         clk_50_clk_clk;                                                         // clk_50:clk_out -> [freq_counter_0:clk, mm_bridge_0:clk, mm_interconnect_0:clk_50_clk_clk, rst_controller_001:clk, rst_controller_002:clk, xcvr_conduit_ctrl_0:clk, xcvr_test_system_0:clk_50_clk]
	wire         clk_100_clk_clk;                                                        // clk_100:clk_out -> [directphy_f_0:reconfig_xcvr_clk, mm_interconnect_0:clk_100_clk_clk, rst_controller:clk, rst_controller_003:clk]
	wire         directphy_f_0_rx_clkout_clk;                                            // directphy_f_0:rx_clkout -> xcvr_st_converter_0:rx_clkout
	wire         xcvr_st_converter_0_rx_clkout_a_output_clk;                             // xcvr_st_converter_0:rx_clkout_a_output -> directphy_f_0:rx_coreclkin
	wire         directphy_f_0_tx_clkout_clk;                                            // directphy_f_0:tx_clkout -> xcvr_st_converter_0:tx_clkout
	wire         xcvr_st_converter_0_tx_clkout_a_output_clk;                             // xcvr_st_converter_0:tx_clkout_a_output -> directphy_f_0:tx_coreclkin
	wire         xcvr_st_converter_0_tx_clkout_sample_clk;                               // xcvr_st_converter_0:tx_clkout_sample -> freq_counter_0:sample_clk
	wire  [63:0] xcvr_st_converter_0_rx_data_a_export;                                   // xcvr_st_converter_0:rx_data_a -> xcvr_test_system_0:data_pattern_checker_0_conduit_pattern_in_export
	wire         xcvr_st_converter_0_rx_clkout_a_export;                                 // xcvr_st_converter_0:rx_clkout_a -> xcvr_test_system_0:data_pattern_checker_0_conduit_pattern_in_clk_export
	wire  [63:0] xcvr_test_system_0_data_pattern_generator_0_conduit_pattern_out_export; // xcvr_test_system_0:data_pattern_generator_0_conduit_pattern_out_export -> xcvr_st_converter_0:tx_data_a
	wire         xcvr_st_converter_0_tx_clkout_a_export;                                 // xcvr_st_converter_0:tx_clkout_a -> xcvr_test_system_0:data_pattern_generator_0_conduit_pattern_out_clk_export
	wire   [0:0] directphy_f_0_rx_is_lockedtodata_rx_is_lockedtodata;                    // directphy_f_0:rx_is_lockedtodata -> xcvr_conduit_ctrl_0:rx_is_lockedtodata
	wire   [0:0] directphy_f_0_rx_is_lockedtoref_rx_is_lockedtoref;                      // directphy_f_0:rx_is_lockedtoref -> xcvr_conduit_ctrl_0:rx_is_lockedtoref
	wire  [79:0] directphy_f_0_rx_parallel_data_rx_parallel_data;                        // directphy_f_0:rx_parallel_data -> xcvr_st_converter_0:rx_parallel_data
	wire   [0:0] directphy_f_0_rx_ready_rx_ready;                                        // directphy_f_0:rx_ready -> xcvr_conduit_ctrl_0:rx_ready
	wire   [0:0] xcvr_conduit_ctrl_0_rx_reset_rx_reset;                                  // xcvr_conduit_ctrl_0:rx_reset -> directphy_f_0:rx_reset
	wire   [0:0] directphy_f_0_rx_reset_ack_rx_reset_ack;                                // directphy_f_0:rx_reset_ack -> xcvr_conduit_ctrl_0:rx_reset_ack
	wire  [79:0] xcvr_st_converter_0_tx_parallel_data_tx_parallel_data;                  // xcvr_st_converter_0:tx_parallel_data -> directphy_f_0:tx_parallel_data
	wire   [0:0] directphy_f_0_tx_pll_locked_tx_pll_locked;                              // directphy_f_0:tx_pll_locked -> xcvr_conduit_ctrl_0:tx_pll_locked
	wire   [0:0] directphy_f_0_tx_ready_tx_ready;                                        // directphy_f_0:tx_ready -> xcvr_conduit_ctrl_0:tx_ready
	wire   [0:0] xcvr_conduit_ctrl_0_tx_reset_tx_reset;                                  // xcvr_conduit_ctrl_0:tx_reset -> directphy_f_0:tx_reset
	wire   [0:0] directphy_f_0_tx_reset_ack_tx_reset_ack;                                // directphy_f_0:tx_reset_ack -> xcvr_conduit_ctrl_0:tx_reset_ack
	wire         clk_50_clk_reset_reset;                                                 // clk_50:reset_n_out -> [rst_controller_001:reset_in0, rst_controller_002:reset_in0, xcvr_test_system_0:reset_50_reset_n]
	wire         mm_bridge_0_m0_waitrequest;                                             // mm_interconnect_0:mm_bridge_0_m0_waitrequest -> mm_bridge_0:m0_waitrequest
	wire  [31:0] mm_bridge_0_m0_readdata;                                                // mm_interconnect_0:mm_bridge_0_m0_readdata -> mm_bridge_0:m0_readdata
	wire         mm_bridge_0_m0_debugaccess;                                             // mm_bridge_0:m0_debugaccess -> mm_interconnect_0:mm_bridge_0_m0_debugaccess
	wire  [20:0] mm_bridge_0_m0_address;                                                 // mm_bridge_0:m0_address -> mm_interconnect_0:mm_bridge_0_m0_address
	wire         mm_bridge_0_m0_read;                                                    // mm_bridge_0:m0_read -> mm_interconnect_0:mm_bridge_0_m0_read
	wire   [3:0] mm_bridge_0_m0_byteenable;                                              // mm_bridge_0:m0_byteenable -> mm_interconnect_0:mm_bridge_0_m0_byteenable
	wire         mm_bridge_0_m0_readdatavalid;                                           // mm_interconnect_0:mm_bridge_0_m0_readdatavalid -> mm_bridge_0:m0_readdatavalid
	wire  [31:0] mm_bridge_0_m0_writedata;                                               // mm_bridge_0:m0_writedata -> mm_interconnect_0:mm_bridge_0_m0_writedata
	wire         mm_bridge_0_m0_write;                                                   // mm_bridge_0:m0_write -> mm_interconnect_0:mm_bridge_0_m0_write
	wire   [0:0] mm_bridge_0_m0_burstcount;                                              // mm_bridge_0:m0_burstcount -> mm_interconnect_0:mm_bridge_0_m0_burstcount
	wire  [31:0] mm_interconnect_0_freq_counter_0_csr_readdata;                          // freq_counter_0:csr_readdata -> mm_interconnect_0:freq_counter_0_csr_readdata
	wire   [3:0] mm_interconnect_0_freq_counter_0_csr_address;                           // mm_interconnect_0:freq_counter_0_csr_address -> freq_counter_0:csr_address
	wire         mm_interconnect_0_freq_counter_0_csr_read;                              // mm_interconnect_0:freq_counter_0_csr_read -> freq_counter_0:csr_read
	wire  [31:0] mm_interconnect_0_xcvr_conduit_ctrl_0_csr_readdata;                     // xcvr_conduit_ctrl_0:csr_readdata -> mm_interconnect_0:xcvr_conduit_ctrl_0_csr_readdata
	wire   [3:0] mm_interconnect_0_xcvr_conduit_ctrl_0_csr_address;                      // mm_interconnect_0:xcvr_conduit_ctrl_0_csr_address -> xcvr_conduit_ctrl_0:csr_address
	wire         mm_interconnect_0_xcvr_conduit_ctrl_0_csr_read;                         // mm_interconnect_0:xcvr_conduit_ctrl_0_csr_read -> xcvr_conduit_ctrl_0:csr_read
	wire         mm_interconnect_0_xcvr_conduit_ctrl_0_csr_write;                        // mm_interconnect_0:xcvr_conduit_ctrl_0_csr_write -> xcvr_conduit_ctrl_0:csr_write
	wire  [31:0] mm_interconnect_0_xcvr_conduit_ctrl_0_csr_writedata;                    // mm_interconnect_0:xcvr_conduit_ctrl_0_csr_writedata -> xcvr_conduit_ctrl_0:csr_writedata
	wire  [31:0] mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_readdata;           // xcvr_test_system_0:mm_bridge_0_s0_readdata -> mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_readdata
	wire         mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_waitrequest;        // xcvr_test_system_0:mm_bridge_0_s0_waitrequest -> mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_waitrequest
	wire         mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_debugaccess;        // mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_debugaccess -> xcvr_test_system_0:mm_bridge_0_s0_debugaccess
	wire  [12:0] mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_address;            // mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_address -> xcvr_test_system_0:mm_bridge_0_s0_address
	wire         mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_read;               // mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_read -> xcvr_test_system_0:mm_bridge_0_s0_read
	wire   [3:0] mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_byteenable;         // mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_byteenable -> xcvr_test_system_0:mm_bridge_0_s0_byteenable
	wire         mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_readdatavalid;      // xcvr_test_system_0:mm_bridge_0_s0_readdatavalid -> mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_readdatavalid
	wire         mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_write;              // mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_write -> xcvr_test_system_0:mm_bridge_0_s0_write
	wire  [31:0] mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_writedata;          // mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_writedata -> xcvr_test_system_0:mm_bridge_0_s0_writedata
	wire   [0:0] mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_burstcount;         // mm_interconnect_0:xcvr_test_system_0_mm_bridge_0_s0_burstcount -> xcvr_test_system_0:mm_bridge_0_s0_burstcount
	wire  [31:0] mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_readdata;            // directphy_f_0:reconfig_xcvr_readdata -> mm_interconnect_0:directphy_f_0_reconfig_xcvr_avmm_readdata
	wire         mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_waitrequest;         // directphy_f_0:reconfig_xcvr_waitrequest -> mm_interconnect_0:directphy_f_0_reconfig_xcvr_avmm_waitrequest
	wire  [17:0] mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_address;             // mm_interconnect_0:directphy_f_0_reconfig_xcvr_avmm_address -> directphy_f_0:reconfig_xcvr_address
	wire         mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_read;                // mm_interconnect_0:directphy_f_0_reconfig_xcvr_avmm_read -> directphy_f_0:reconfig_xcvr_read
	wire   [3:0] mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_byteenable;          // mm_interconnect_0:directphy_f_0_reconfig_xcvr_avmm_byteenable -> directphy_f_0:reconfig_xcvr_byteenable
	wire         mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_write;               // mm_interconnect_0:directphy_f_0_reconfig_xcvr_avmm_write -> directphy_f_0:reconfig_xcvr_write
	wire  [31:0] mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_writedata;           // mm_interconnect_0:directphy_f_0_reconfig_xcvr_avmm_writedata -> directphy_f_0:reconfig_xcvr_writedata
	wire         rst_controller_reset_out_reset;                                         // rst_controller:reset_out -> directphy_f_0:reconfig_xcvr_reset
	wire         clk_100_clk_reset_reset;                                                // clk_100:reset_n_out -> [rst_controller:reset_in0, rst_controller_003:reset_in0]
	wire         rst_controller_001_reset_out_reset;                                     // rst_controller_001:reset_out -> [freq_counter_0:reset_n, mm_bridge_0:reset, xcvr_conduit_ctrl_0:reset_n]
	wire         rst_controller_002_reset_out_reset;                                     // rst_controller_002:reset_out -> [mm_interconnect_0:mm_bridge_0_m0_translator_reset_reset_bridge_in_reset_reset, mm_interconnect_0:mm_bridge_0_reset_reset_bridge_in_reset_reset]
	wire         rst_controller_003_reset_out_reset;                                     // rst_controller_003:reset_out -> [mm_interconnect_0:directphy_f_0_reconfig_xcvr_avmm_translator_reset_reset_bridge_in_reset_reset, mm_interconnect_0:directphy_f_0_reconfig_xcvr_reset_reset_bridge_in_reset_reset]

	ftile_xcvr_test_clk_100_0 clk_100 (
		.in_clk      (clk_100_clk),             //   input,  width = 1,       clk_in.clk
		.reset_n     (reset_100_reset_n),       //   input,  width = 1, clk_in_reset.reset_n
		.clk_out     (clk_100_clk_clk),         //  output,  width = 1,          clk.clk
		.reset_n_out (clk_100_clk_reset_reset)  //  output,  width = 1,    clk_reset.reset_n
	);

	ftile_xcvr_test_clk_50_0 clk_50 (
		.in_clk      (clk_50_clk),             //   input,  width = 1,       clk_in.clk
		.reset_n     (reset_50_reset_n),       //   input,  width = 1, clk_in_reset.reset_n
		.clk_out     (clk_50_clk_clk),         //  output,  width = 1,          clk.clk
		.reset_n_out (clk_50_clk_reset_reset)  //  output,  width = 1,    clk_reset.reset_n
	);

	ftile_xcvr_test_directphy_f_0 directphy_f_0 (
		.rx_cdr_refclk_link        (directphy_f_0_rx_cdr_refclk_link_clk),                           //   input,   width = 1,  rx_cdr_refclk_link.clk
		.tx_pll_refclk_link        (directphy_f_0_tx_pll_refclk_link_clk),                           //   input,   width = 1,  tx_pll_refclk_link.clk
		.system_pll_clk_link       (directphy_f_0_system_pll_clk_link_clk),                          //   input,   width = 1, system_pll_clk_link.clk
		.tx_reset                  (xcvr_conduit_ctrl_0_tx_reset_tx_reset),                          //   input,   width = 1,            tx_reset.tx_reset
		.rx_reset                  (xcvr_conduit_ctrl_0_rx_reset_rx_reset),                          //   input,   width = 1,            rx_reset.rx_reset
		.tx_reset_ack              (directphy_f_0_tx_reset_ack_tx_reset_ack),                        //  output,   width = 1,        tx_reset_ack.tx_reset_ack
		.rx_reset_ack              (directphy_f_0_rx_reset_ack_rx_reset_ack),                        //  output,   width = 1,        rx_reset_ack.rx_reset_ack
		.tx_ready                  (directphy_f_0_tx_ready_tx_ready),                                //  output,   width = 1,            tx_ready.tx_ready
		.rx_ready                  (directphy_f_0_rx_ready_rx_ready),                                //  output,   width = 1,            rx_ready.rx_ready
		.tx_coreclkin              (xcvr_st_converter_0_tx_clkout_a_output_clk),                     //   input,   width = 1,        tx_coreclkin.clk
		.rx_coreclkin              (xcvr_st_converter_0_rx_clkout_a_output_clk),                     //   input,   width = 1,        rx_coreclkin.clk
		.tx_clkout                 (directphy_f_0_tx_clkout_clk),                                    //  output,   width = 1,           tx_clkout.clk
		.rx_clkout                 (directphy_f_0_rx_clkout_clk),                                    //  output,   width = 1,           rx_clkout.clk
		.tx_serial_data            (directphy_f_0_tx_serial_data_tx_serial_data),                    //  output,   width = 1,      tx_serial_data.tx_serial_data
		.tx_serial_data_n          (directphy_f_0_tx_serial_data_n_tx_serial_data_n),                //  output,   width = 1,    tx_serial_data_n.tx_serial_data_n
		.rx_serial_data            (directphy_f_0_rx_serial_data_rx_serial_data),                    //   input,   width = 1,      rx_serial_data.rx_serial_data
		.rx_serial_data_n          (directphy_f_0_rx_serial_data_n_rx_serial_data_n),                //   input,   width = 1,    rx_serial_data_n.rx_serial_data_n
		.tx_pll_locked             (directphy_f_0_tx_pll_locked_tx_pll_locked),                      //  output,   width = 1,       tx_pll_locked.tx_pll_locked
		.rx_is_lockedtodata        (directphy_f_0_rx_is_lockedtodata_rx_is_lockedtodata),            //  output,   width = 1,  rx_is_lockedtodata.rx_is_lockedtodata
		.rx_is_lockedtoref         (directphy_f_0_rx_is_lockedtoref_rx_is_lockedtoref),              //  output,   width = 1,   rx_is_lockedtoref.rx_is_lockedtoref
		.tx_parallel_data          (xcvr_st_converter_0_tx_parallel_data_tx_parallel_data),          //   input,  width = 80,    tx_parallel_data.tx_parallel_data
		.rx_parallel_data          (directphy_f_0_rx_parallel_data_rx_parallel_data),                //  output,  width = 80,    rx_parallel_data.rx_parallel_data
		.reconfig_xcvr_clk         (clk_100_clk_clk),                                                //   input,   width = 1,   reconfig_xcvr_clk.clk
		.reconfig_xcvr_reset       (rst_controller_reset_out_reset),                                 //   input,   width = 1, reconfig_xcvr_reset.reset
		.reconfig_xcvr_write       (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_write),       //   input,   width = 1,  reconfig_xcvr_avmm.write
		.reconfig_xcvr_read        (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_read),        //   input,   width = 1,                    .read
		.reconfig_xcvr_address     (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_address),     //   input,  width = 18,                    .address
		.reconfig_xcvr_byteenable  (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_byteenable),  //   input,   width = 4,                    .byteenable
		.reconfig_xcvr_writedata   (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_writedata),   //   input,  width = 32,                    .writedata
		.reconfig_xcvr_readdata    (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_readdata),    //  output,  width = 32,                    .readdata
		.reconfig_xcvr_waitrequest (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_waitrequest)  //  output,   width = 1,                    .waitrequest
	);

	ftile_xcvr_test_freq_counter_0 freq_counter_0 (
		.reset_n      (~rst_controller_001_reset_out_reset),           //   input,   width = 1,        reset.reset_n
		.clk          (clk_50_clk_clk),                                //   input,   width = 1,        clock.clk
		.csr_address  (mm_interconnect_0_freq_counter_0_csr_address),  //   input,   width = 4,          csr.address
		.csr_read     (mm_interconnect_0_freq_counter_0_csr_read),     //   input,   width = 1,             .read
		.csr_readdata (mm_interconnect_0_freq_counter_0_csr_readdata), //  output,  width = 32,             .readdata
		.sample_clk   (xcvr_st_converter_0_tx_clkout_sample_clk)       //   input,   width = 1, sample_clock.clk
	);

	ftile_xcvr_test_mm_bridge_0 mm_bridge_0 (
		.clk              (clk_50_clk_clk),                     //   input,   width = 1,   clk.clk
		.reset            (rst_controller_001_reset_out_reset), //   input,   width = 1, reset.reset
		.s0_waitrequest   (mm_bridge_0_s0_waitrequest),         //  output,   width = 1,    s0.waitrequest
		.s0_readdata      (mm_bridge_0_s0_readdata),            //  output,  width = 32,      .readdata
		.s0_readdatavalid (mm_bridge_0_s0_readdatavalid),       //  output,   width = 1,      .readdatavalid
		.s0_burstcount    (mm_bridge_0_s0_burstcount),          //   input,   width = 1,      .burstcount
		.s0_writedata     (mm_bridge_0_s0_writedata),           //   input,  width = 32,      .writedata
		.s0_address       (mm_bridge_0_s0_address),             //   input,  width = 21,      .address
		.s0_write         (mm_bridge_0_s0_write),               //   input,   width = 1,      .write
		.s0_read          (mm_bridge_0_s0_read),                //   input,   width = 1,      .read
		.s0_byteenable    (mm_bridge_0_s0_byteenable),          //   input,   width = 4,      .byteenable
		.s0_debugaccess   (mm_bridge_0_s0_debugaccess),         //   input,   width = 1,      .debugaccess
		.m0_waitrequest   (mm_bridge_0_m0_waitrequest),         //   input,   width = 1,    m0.waitrequest
		.m0_readdata      (mm_bridge_0_m0_readdata),            //   input,  width = 32,      .readdata
		.m0_readdatavalid (mm_bridge_0_m0_readdatavalid),       //   input,   width = 1,      .readdatavalid
		.m0_burstcount    (mm_bridge_0_m0_burstcount),          //  output,   width = 1,      .burstcount
		.m0_writedata     (mm_bridge_0_m0_writedata),           //  output,  width = 32,      .writedata
		.m0_address       (mm_bridge_0_m0_address),             //  output,  width = 21,      .address
		.m0_write         (mm_bridge_0_m0_write),               //  output,   width = 1,      .write
		.m0_read          (mm_bridge_0_m0_read),                //  output,   width = 1,      .read
		.m0_byteenable    (mm_bridge_0_m0_byteenable),          //  output,   width = 4,      .byteenable
		.m0_debugaccess   (mm_bridge_0_m0_debugaccess)          //  output,   width = 1,      .debugaccess
	);

	ftile_xcvr_test_xcvr_conduit_ctrl_0 xcvr_conduit_ctrl_0 (
		.reset_n            (~rst_controller_001_reset_out_reset),                 //   input,   width = 1,              reset.reset_n
		.clk                (clk_50_clk_clk),                                      //   input,   width = 1,              clock.clk
		.csr_address        (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_address),   //   input,   width = 4,                csr.address
		.csr_read           (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_read),      //   input,   width = 1,                   .read
		.csr_write          (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_write),     //   input,   width = 1,                   .write
		.csr_readdata       (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_readdata),  //  output,  width = 32,                   .readdata
		.csr_writedata      (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_writedata), //   input,  width = 32,                   .writedata
		.tx_pll_locked      (directphy_f_0_tx_pll_locked_tx_pll_locked),           //   input,   width = 1,      tx_pll_locked.tx_pll_locked
		.rx_is_lockedtoref  (directphy_f_0_rx_is_lockedtoref_rx_is_lockedtoref),   //   input,   width = 1,  rx_is_lockedtoref.rx_is_lockedtoref
		.rx_is_lockedtodata (directphy_f_0_rx_is_lockedtodata_rx_is_lockedtodata), //   input,   width = 1, rx_is_lockedtodata.rx_is_lockedtodata
		.tx_reset           (xcvr_conduit_ctrl_0_tx_reset_tx_reset),               //  output,   width = 1,           tx_reset.tx_reset
		.tx_reset_ack       (directphy_f_0_tx_reset_ack_tx_reset_ack),             //   input,   width = 1,       tx_reset_ack.tx_reset_ack
		.tx_ready           (directphy_f_0_tx_ready_tx_ready),                     //   input,   width = 1,           tx_ready.tx_ready
		.rx_reset           (xcvr_conduit_ctrl_0_rx_reset_rx_reset),               //  output,   width = 1,           rx_reset.rx_reset
		.rx_reset_ack       (directphy_f_0_rx_reset_ack_rx_reset_ack),             //   input,   width = 1,       rx_reset_ack.rx_reset_ack
		.rx_ready           (directphy_f_0_rx_ready_rx_ready)                      //   input,   width = 1,           rx_ready.rx_ready
	);

	ftile_xcvr_test_xcvr_st_converter_0 xcvr_st_converter_0 (
		.tx_parallel_data   (xcvr_st_converter_0_tx_parallel_data_tx_parallel_data),                  //  output,  width = 80,   tx_parallel_data.tx_parallel_data
		.tx_clkout          (directphy_f_0_tx_clkout_clk),                                            //   input,   width = 1,          tx_clkout.clk
		.rx_parallel_data   (directphy_f_0_rx_parallel_data_rx_parallel_data),                        //   input,  width = 80,   rx_parallel_data.rx_parallel_data
		.rx_clkout          (directphy_f_0_rx_clkout_clk),                                            //   input,   width = 1,          rx_clkout.clk
		.tx_data_a          (xcvr_test_system_0_data_pattern_generator_0_conduit_pattern_out_export), //   input,  width = 64,          tx_data_a.export
		.tx_clkout_a        (xcvr_st_converter_0_tx_clkout_a_export),                                 //  output,   width = 1,        tx_clkout_a.export
		.rx_data_a          (xcvr_st_converter_0_rx_data_a_export),                                   //  output,  width = 64,          rx_data_a.export
		.rx_clkout_a        (xcvr_st_converter_0_rx_clkout_a_export),                                 //  output,   width = 1,        rx_clkout_a.export
		.tx_clkout_sample   (xcvr_st_converter_0_tx_clkout_sample_clk),                               //  output,   width = 1,   tx_clkout_sample.clk
		.tx_clkout_a_output (xcvr_st_converter_0_tx_clkout_a_output_clk),                             //  output,   width = 1, tx_clkout_a_output.clk
		.rx_clkout_a_output (xcvr_st_converter_0_rx_clkout_a_output_clk)                              //  output,   width = 1, rx_clkout_a_output.clk
	);

	xcvr_test_system xcvr_test_system_0 (
		.clk_50_clk                                              (clk_50_clk_clk),                                                         //   input,   width = 1,                                           clk_50.clk
		.reset_50_reset_n                                        (clk_50_clk_reset_reset),                                                 //   input,   width = 1,                                         reset_50.reset_n
		.data_pattern_checker_0_conduit_pattern_in_clk_export    (xcvr_st_converter_0_rx_clkout_a_export),                                 //   input,   width = 1,    data_pattern_checker_0_conduit_pattern_in_clk.export
		.data_pattern_checker_0_conduit_pattern_in_export        (xcvr_st_converter_0_rx_data_a_export),                                   //   input,  width = 64,        data_pattern_checker_0_conduit_pattern_in.export
		.data_pattern_generator_0_conduit_pattern_out_clk_export (xcvr_st_converter_0_tx_clkout_a_export),                                 //   input,   width = 1, data_pattern_generator_0_conduit_pattern_out_clk.export
		.data_pattern_generator_0_conduit_pattern_out_export     (xcvr_test_system_0_data_pattern_generator_0_conduit_pattern_out_export), //  output,  width = 64,     data_pattern_generator_0_conduit_pattern_out.export
		.mm_bridge_0_s0_waitrequest                              (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_waitrequest),        //  output,   width = 1,                                   mm_bridge_0_s0.waitrequest
		.mm_bridge_0_s0_readdata                                 (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_readdata),           //  output,  width = 32,                                                 .readdata
		.mm_bridge_0_s0_readdatavalid                            (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_readdatavalid),      //  output,   width = 1,                                                 .readdatavalid
		.mm_bridge_0_s0_burstcount                               (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_burstcount),         //   input,   width = 1,                                                 .burstcount
		.mm_bridge_0_s0_writedata                                (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_writedata),          //   input,  width = 32,                                                 .writedata
		.mm_bridge_0_s0_address                                  (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_address),            //   input,  width = 13,                                                 .address
		.mm_bridge_0_s0_write                                    (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_write),              //   input,   width = 1,                                                 .write
		.mm_bridge_0_s0_read                                     (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_read),               //   input,   width = 1,                                                 .read
		.mm_bridge_0_s0_byteenable                               (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_byteenable),         //   input,   width = 4,                                                 .byteenable
		.mm_bridge_0_s0_debugaccess                              (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_debugaccess)         //   input,   width = 1,                                                 .debugaccess
	);

	ftile_xcvr_test_altera_mm_interconnect_1920_vhezstq mm_interconnect_0 (
		.mm_bridge_0_m0_address                                                        (mm_bridge_0_m0_address),                                            //   input,  width = 21,                                                          mm_bridge_0_m0.address
		.mm_bridge_0_m0_waitrequest                                                    (mm_bridge_0_m0_waitrequest),                                        //  output,   width = 1,                                                                        .waitrequest
		.mm_bridge_0_m0_burstcount                                                     (mm_bridge_0_m0_burstcount),                                         //   input,   width = 1,                                                                        .burstcount
		.mm_bridge_0_m0_byteenable                                                     (mm_bridge_0_m0_byteenable),                                         //   input,   width = 4,                                                                        .byteenable
		.mm_bridge_0_m0_read                                                           (mm_bridge_0_m0_read),                                               //   input,   width = 1,                                                                        .read
		.mm_bridge_0_m0_readdata                                                       (mm_bridge_0_m0_readdata),                                           //  output,  width = 32,                                                                        .readdata
		.mm_bridge_0_m0_readdatavalid                                                  (mm_bridge_0_m0_readdatavalid),                                      //  output,   width = 1,                                                                        .readdatavalid
		.mm_bridge_0_m0_write                                                          (mm_bridge_0_m0_write),                                              //   input,   width = 1,                                                                        .write
		.mm_bridge_0_m0_writedata                                                      (mm_bridge_0_m0_writedata),                                          //   input,  width = 32,                                                                        .writedata
		.mm_bridge_0_m0_debugaccess                                                    (mm_bridge_0_m0_debugaccess),                                        //   input,   width = 1,                                                                        .debugaccess
		.freq_counter_0_csr_address                                                    (mm_interconnect_0_freq_counter_0_csr_address),                      //  output,   width = 4,                                                      freq_counter_0_csr.address
		.freq_counter_0_csr_read                                                       (mm_interconnect_0_freq_counter_0_csr_read),                         //  output,   width = 1,                                                                        .read
		.freq_counter_0_csr_readdata                                                   (mm_interconnect_0_freq_counter_0_csr_readdata),                     //   input,  width = 32,                                                                        .readdata
		.xcvr_conduit_ctrl_0_csr_address                                               (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_address),                 //  output,   width = 4,                                                 xcvr_conduit_ctrl_0_csr.address
		.xcvr_conduit_ctrl_0_csr_write                                                 (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_write),                   //  output,   width = 1,                                                                        .write
		.xcvr_conduit_ctrl_0_csr_read                                                  (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_read),                    //  output,   width = 1,                                                                        .read
		.xcvr_conduit_ctrl_0_csr_readdata                                              (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_readdata),                //   input,  width = 32,                                                                        .readdata
		.xcvr_conduit_ctrl_0_csr_writedata                                             (mm_interconnect_0_xcvr_conduit_ctrl_0_csr_writedata),               //  output,  width = 32,                                                                        .writedata
		.xcvr_test_system_0_mm_bridge_0_s0_address                                     (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_address),       //  output,  width = 13,                                       xcvr_test_system_0_mm_bridge_0_s0.address
		.xcvr_test_system_0_mm_bridge_0_s0_write                                       (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_write),         //  output,   width = 1,                                                                        .write
		.xcvr_test_system_0_mm_bridge_0_s0_read                                        (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_read),          //  output,   width = 1,                                                                        .read
		.xcvr_test_system_0_mm_bridge_0_s0_readdata                                    (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_readdata),      //   input,  width = 32,                                                                        .readdata
		.xcvr_test_system_0_mm_bridge_0_s0_writedata                                   (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_writedata),     //  output,  width = 32,                                                                        .writedata
		.xcvr_test_system_0_mm_bridge_0_s0_burstcount                                  (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_burstcount),    //  output,   width = 1,                                                                        .burstcount
		.xcvr_test_system_0_mm_bridge_0_s0_byteenable                                  (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_byteenable),    //  output,   width = 4,                                                                        .byteenable
		.xcvr_test_system_0_mm_bridge_0_s0_readdatavalid                               (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_readdatavalid), //   input,   width = 1,                                                                        .readdatavalid
		.xcvr_test_system_0_mm_bridge_0_s0_waitrequest                                 (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_waitrequest),   //   input,   width = 1,                                                                        .waitrequest
		.xcvr_test_system_0_mm_bridge_0_s0_debugaccess                                 (mm_interconnect_0_xcvr_test_system_0_mm_bridge_0_s0_debugaccess),   //  output,   width = 1,                                                                        .debugaccess
		.directphy_f_0_reconfig_xcvr_avmm_address                                      (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_address),        //  output,  width = 18,                                        directphy_f_0_reconfig_xcvr_avmm.address
		.directphy_f_0_reconfig_xcvr_avmm_write                                        (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_write),          //  output,   width = 1,                                                                        .write
		.directphy_f_0_reconfig_xcvr_avmm_read                                         (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_read),           //  output,   width = 1,                                                                        .read
		.directphy_f_0_reconfig_xcvr_avmm_readdata                                     (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_readdata),       //   input,  width = 32,                                                                        .readdata
		.directphy_f_0_reconfig_xcvr_avmm_writedata                                    (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_writedata),      //  output,  width = 32,                                                                        .writedata
		.directphy_f_0_reconfig_xcvr_avmm_byteenable                                   (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_byteenable),     //  output,   width = 4,                                                                        .byteenable
		.directphy_f_0_reconfig_xcvr_avmm_waitrequest                                  (mm_interconnect_0_directphy_f_0_reconfig_xcvr_avmm_waitrequest),    //   input,   width = 1,                                                                        .waitrequest
		.mm_bridge_0_reset_reset_bridge_in_reset_reset                                 (rst_controller_002_reset_out_reset),                                //   input,   width = 1,                                 mm_bridge_0_reset_reset_bridge_in_reset.reset
		.directphy_f_0_reconfig_xcvr_reset_reset_bridge_in_reset_reset                 (rst_controller_003_reset_out_reset),                                //   input,   width = 1,                 directphy_f_0_reconfig_xcvr_reset_reset_bridge_in_reset.reset
		.mm_bridge_0_m0_translator_reset_reset_bridge_in_reset_reset                   (rst_controller_002_reset_out_reset),                                //   input,   width = 1,                   mm_bridge_0_m0_translator_reset_reset_bridge_in_reset.reset
		.directphy_f_0_reconfig_xcvr_avmm_translator_reset_reset_bridge_in_reset_reset (rst_controller_003_reset_out_reset),                                //   input,   width = 1, directphy_f_0_reconfig_xcvr_avmm_translator_reset_reset_bridge_in_reset.reset
		.clk_50_clk_clk                                                                (clk_50_clk_clk),                                                    //   input,   width = 1,                                                              clk_50_clk.clk
		.clk_100_clk_clk                                                               (clk_100_clk_clk)                                                    //   input,   width = 1,                                                             clk_100_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~clk_100_clk_reset_reset),       //   input,  width = 1, reset_in0.reset
		.clk            (clk_100_clk_clk),                //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                               // (terminated),                       
		.reset_req_in0  (1'b0),                           // (terminated),                       
		.reset_in1      (1'b0),                           // (terminated),                       
		.reset_req_in1  (1'b0),                           // (terminated),                       
		.reset_in2      (1'b0),                           // (terminated),                       
		.reset_req_in2  (1'b0),                           // (terminated),                       
		.reset_in3      (1'b0),                           // (terminated),                       
		.reset_req_in3  (1'b0),                           // (terminated),                       
		.reset_in4      (1'b0),                           // (terminated),                       
		.reset_req_in4  (1'b0),                           // (terminated),                       
		.reset_in5      (1'b0),                           // (terminated),                       
		.reset_req_in5  (1'b0),                           // (terminated),                       
		.reset_in6      (1'b0),                           // (terminated),                       
		.reset_req_in6  (1'b0),                           // (terminated),                       
		.reset_in7      (1'b0),                           // (terminated),                       
		.reset_req_in7  (1'b0),                           // (terminated),                       
		.reset_in8      (1'b0),                           // (terminated),                       
		.reset_req_in8  (1'b0),                           // (terminated),                       
		.reset_in9      (1'b0),                           // (terminated),                       
		.reset_req_in9  (1'b0),                           // (terminated),                       
		.reset_in10     (1'b0),                           // (terminated),                       
		.reset_req_in10 (1'b0),                           // (terminated),                       
		.reset_in11     (1'b0),                           // (terminated),                       
		.reset_req_in11 (1'b0),                           // (terminated),                       
		.reset_in12     (1'b0),                           // (terminated),                       
		.reset_req_in12 (1'b0),                           // (terminated),                       
		.reset_in13     (1'b0),                           // (terminated),                       
		.reset_req_in13 (1'b0),                           // (terminated),                       
		.reset_in14     (1'b0),                           // (terminated),                       
		.reset_req_in14 (1'b0),                           // (terminated),                       
		.reset_in15     (1'b0),                           // (terminated),                       
		.reset_req_in15 (1'b0)                            // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~clk_50_clk_reset_reset),            //   input,  width = 1, reset_in0.reset
		.clk            (clk_50_clk_clk),                     //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                                   // (terminated),                       
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (~clk_50_clk_reset_reset),            //   input,  width = 1, reset_in0.reset
		.clk            (clk_50_clk_clk),                     //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                                   // (terminated),                       
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_003 (
		.reset_in0      (~clk_100_clk_reset_reset),           //   input,  width = 1, reset_in0.reset
		.clk            (clk_100_clk_clk),                    //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_003_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                                   // (terminated),                       
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

endmodule
